version: "3.8"

services:
  nginx:
    container_name: vitreo_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    container_name: vitreo_db
    image: postgres:14.8-alpine
    env_file: .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    container_name: vitreo_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    command: >
      sh -c "python3 manage.py migrate --no-input && gunicorn --bind 0.0.0.0:8000 CoreRoot.wsgi:application"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      - db

volumes:
  uploads_volume:
  postgres_data:
