# Generated by Django 4.0.1 on 2023-07-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_edited'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
